// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4kz9OloGVO1Q7liOpxpQtzKyg1RUsMFI',
    appId: '1:509809459103:web:62d6243f8e2b9d84d907aa',
    messagingSenderId: '509809459103',
    projectId: 'chat-app-96d9a',
    authDomain: 'chat-app-96d9a.firebaseapp.com',
    storageBucket: 'chat-app-96d9a.appspot.com',
    measurementId: 'G-RYLYJ0DZDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGsUwhZqkghQ1xGSD2pB3Ai1nXaHfujd0',
    appId: '1:509809459103:android:8fa222a6dca9f311d907aa',
    messagingSenderId: '509809459103',
    projectId: 'chat-app-96d9a',
    storageBucket: 'chat-app-96d9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGIRcL4zi0dI9Q4gCUC7KEusLD5eX3Fk',
    appId: '1:509809459103:ios:ac38c0b4ac57d80ed907aa',
    messagingSenderId: '509809459103',
    projectId: 'chat-app-96d9a',
    storageBucket: 'chat-app-96d9a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBGIRcL4zi0dI9Q4gCUC7KEusLD5eX3Fk',
    appId: '1:509809459103:ios:ac38c0b4ac57d80ed907aa',
    messagingSenderId: '509809459103',
    projectId: 'chat-app-96d9a',
    storageBucket: 'chat-app-96d9a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4kz9OloGVO1Q7liOpxpQtzKyg1RUsMFI',
    appId: '1:509809459103:web:18d7db226ee19becd907aa',
    messagingSenderId: '509809459103',
    projectId: 'chat-app-96d9a',
    authDomain: 'chat-app-96d9a.firebaseapp.com',
    storageBucket: 'chat-app-96d9a.appspot.com',
    measurementId: 'G-6XJ3PF9YGM',
  );
}
